### ISSUE TITLE
Many packages don't follow the naming scheme

### ISSUE THREAD

**Issue by basnijholt** [custom-components/information#15]
According to [this](https://github.com/custom-components/information#rules) rule, integrations should have a name like `component.platform`.

A large fraction of the packages under the custom-components namespace do not follow this convention.

Should we somehow enforce this? GitHub will remember the old name and just automatically forward all trafifc.

**Comment by ludeeus** [comment]
Correct, the section there is in need of an update.

The reason for that rule was that custom_updater that used this org as a based needed it.
That has been deprecated, and that rule is no longer needed.

after the great migration in HA, the structure also changed from:
platform/integration (ie mediaplayer.xxxx)

to integration/platfrom (ie xxxx.mediaplayer)

If enforcement should be in place it should now rather be `xxxx` for the repo name, then a single repo have multiple platforms for that integration
