### ISSUE TITLE
sensor.trakt pointing to wrong release

### ISSUE THREAD

**Issue by jOOc** [custom-components/information#3]
**Version of the cusom_component**

**Describe the bug**
The sensor.trakt component pointing to 0.0.2. But as far as I can see no release is available yet.

![image](https://user-images.githubusercontent.com/9382342/45238426-12a5aa00-b2e2-11e8-9ead-02f482370c26.png)

**log**

```
Add your logs here.
```

**Comment by ludeeus** [comment]
The component get's that data from inside the .py file
<https://github.com/custom-components/sensor.trakt/blob/master/custom_components/sensor/trakt.py#L18>
So this is not wrong.
We are multiple people adding components to this org, not all of us are using GH releases.
maybe @iantrich want to start with that now? :D

**Comment by iantrich** [comment]
What is there to be gained for putting out a GH release if the updater grabs from the .py file? Changelogs?

**Comment by ludeeus** [comment]
@jOOc care to answer that, since you "requested" it?

_The reason I use it is "old" habits :P_

**Comment by jOOc** [comment]
I was just wondering.
As many custom components dont use releases just point the link to the GH repo instead of the releases as you do on some of the custom cards.

**Comment by ludeeus** [comment]
When I made the script that generate those links, GH redirected you to the Repo page when there was no releases. It looks like they have changed this now.
