### ISSUE TITLE
Org Icon suggestion

### ISSUE THREAD

**Issue by Gluwc** [custom-components/information#9]
**Is your feature request related to a problem? Please describe.**
The problem is this org not having a nice icon.

**Describe the solution you'd like**
Use attached custom icon.

**Describe alternatives you've considered**
Be disappointed by the default github icon.
![custom-components](https://user-images.githubusercontent.com/38736396/55487251-0d1d0200-562e-11e9-898c-10ab40dece89.png)

**Comment by iantrich** [comment]
Nice

**Comment by ludeeus** [comment]
He does :D

Thanks @Gluwc 
![image](https://user-images.githubusercontent.com/15093472/55489859-0349cd80-5633-11e9-846a-daf40ca73b76.png)
